// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	PrincipalID pgtype.UUID        `json:"principal_id"`
	ActionID    string             `json:"action_id"`
	RequestHash string             `json:"request_hash"`
	Receipt     []byte             `json:"receipt"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AgentExecutionPolicy struct {
	PrincipalID      pgtype.UUID `json:"principal_id"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ProactiveEnabled bool        `json:"proactive_enabled"`
	Version          int64       `json:"version"`
}

type Event struct {
	ID          int64              `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	PrincipalID pgtype.UUID        `json:"principal_id"`
	ActionID    string             `json:"action_id"`
	Type        string             `json:"type"`
	Data        []byte             `json:"data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExecutionAction struct {
	RunID       pgtype.UUID        `json:"run_id"`
	ActionID    string             `json:"action_id"`
	RequestHash string             `json:"request_hash"`
	ActionType  string             `json:"action_type"`
	Payload     []byte             `json:"payload"`
	Receipt     []byte             `json:"receipt"`
	MessageID   pgtype.UUID        `json:"message_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExecutionArchive struct {
	ID              pgtype.UUID        `json:"id"`
	RunID           pgtype.UUID        `json:"run_id"`
	ThroughSeq      int64              `json:"through_seq"`
	TargetBinding   string             `json:"target_binding"`
	RendererVersion string             `json:"renderer_version"`
	RunSnapshot     []byte             `json:"run_snapshot"`
	ManifestHash    string             `json:"manifest_hash"`
	PreparedBy      pgtype.UUID        `json:"prepared_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ExecutionArchiveCursor struct {
	RunID           pgtype.UUID        `json:"run_id"`
	TargetBinding   string             `json:"target_binding"`
	VerifiedThrough int64              `json:"verified_through"`
	ArchiveID       pgtype.UUID        `json:"archive_id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ExecutionArchivePart struct {
	ArchiveID           pgtype.UUID        `json:"archive_id"`
	Part                int32              `json:"part"`
	Title               string             `json:"title"`
	Content             string             `json:"content"`
	ContentHash         string             `json:"content_hash"`
	State               string             `json:"state"`
	ClaimToken          pgtype.UUID        `json:"claim_token"`
	RequestStartedAt    pgtype.Timestamptz `json:"request_started_at"`
	LeaseExpiresAt      pgtype.Timestamptz `json:"lease_expires_at"`
	ExternalID          string             `json:"external_id"`
	ObservedContentHash string             `json:"observed_content_hash"`
	ObservedTitleHash   string             `json:"observed_title_hash"`
	ErrorCode           string             `json:"error_code"`
	Attempts            int32              `json:"attempts"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ExecutionArchiveTargetConfig struct {
	BindingID  string             `json:"binding_id"`
	ConfigHash string             `json:"config_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ExecutionEvent struct {
	RunID       pgtype.UUID        `json:"run_id"`
	EventID     string             `json:"event_id"`
	RequestHash string             `json:"request_hash"`
	Event       []byte             `json:"event"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExecutionEvidenceEntry struct {
	RunID          pgtype.UUID        `json:"run_id"`
	Seq            int64              `json:"seq"`
	Kind           string             `json:"kind"`
	ObjectID       string             `json:"object_id"`
	Data           []byte             `json:"data"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	LegacySnapshot bool               `json:"legacy_snapshot"`
}

type ExecutionRun struct {
	ID              pgtype.UUID        `json:"id"`
	ExecutorID      pgtype.UUID        `json:"executor_id"`
	PrincipalID     pgtype.UUID        `json:"principal_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ExecutorVersion int64              `json:"executor_version"`
	PolicyVersion   int64              `json:"policy_version"`
	ParentRunID     pgtype.UUID        `json:"parent_run_id"`
	Context         []byte             `json:"context"`
	Goal            string             `json:"goal"`
	Status          string             `json:"status"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EvidenceSeq     int64              `json:"evidence_seq"`
}

type Executor struct {
	ID              pgtype.UUID        `json:"id"`
	Issuer          string             `json:"issuer"`
	MachineSubject  string             `json:"machine_subject"`
	PrincipalID     pgtype.UUID        `json:"principal_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Enabled         bool               `json:"enabled"`
	Version         int64              `json:"version"`
	RuntimeVersion  string             `json:"runtime_version"`
	WorkflowVersion string             `json:"workflow_version"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ExternalIdentity struct {
	Issuer      string      `json:"issuer"`
	Subject     string      `json:"subject"`
	PrincipalID pgtype.UUID `json:"principal_id"`
}

type Message struct {
	ID              pgtype.UUID        `json:"id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	Content         string             `json:"content"`
	Seq             int64              `json:"seq"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ReplyTo         pgtype.UUID        `json:"reply_to"`
	ReplySnapshot   []byte             `json:"reply_snapshot"`
	ReactionVersion int64              `json:"reaction_version"`
}

type MessageReaction struct {
	MessageID   pgtype.UUID        `json:"message_id"`
	PrincipalID pgtype.UUID        `json:"principal_id"`
	Emoji       string             `json:"emoji"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Principal struct {
	ID             pgtype.UUID        `json:"id"`
	Kind           string             `json:"kind"`
	DisplayName    string             `json:"display_name"`
	Disabled       bool               `json:"disabled"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ProfileVersion int64              `json:"profile_version"`
}

type Room struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Title        string             `json:"title"`
	Kind         string             `json:"kind"`
	Version      int64              `json:"version"`
	ScopeEpoch   int64              `json:"scope_epoch"`
	Stopped      bool               `json:"stopped"`
	RequireHuman bool               `json:"require_human"`
	Seq          int64              `json:"seq"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	RoomID      pgtype.UUID `json:"room_id"`
	PrincipalID pgtype.UUID `json:"principal_id"`
	Role        string      `json:"role"`
}

type TransportBridgeStatus struct {
	BridgeID        string             `json:"bridge_id"`
	ReceiverID      pgtype.UUID        `json:"receiver_id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	ConnectionState string             `json:"connection_state"`
	HeartbeatAt     pgtype.Timestamptz `json:"heartbeat_at"`
	HeartbeatSeq    int64              `json:"heartbeat_seq"`
}

type TransportInbox struct {
	ID                 int64              `json:"id"`
	BridgeID           string             `json:"bridge_id"`
	ReceiverID         pgtype.UUID        `json:"receiver_id"`
	RoomID             pgtype.UUID        `json:"room_id"`
	MessageID          pgtype.UUID        `json:"message_id"`
	EventID            int64              `json:"event_id"`
	ProviderUid        string             `json:"provider_uid"`
	Kind               string             `json:"kind"`
	ObservedScopeEpoch int64              `json:"observed_scope_epoch"`
	SdkReceivedTime    int64              `json:"sdk_received_time"`
	EnvelopeSha256     string             `json:"envelope_sha256"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
}

type TransportOutbox struct {
	ID                 int64              `json:"id"`
	EventID            int64              `json:"event_id"`
	Provider           string             `json:"provider"`
	Status             string             `json:"status"`
	Attempts           int32              `json:"attempts"`
	ProviderReceipt    []byte             `json:"provider_receipt"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ClaimToken         pgtype.UUID        `json:"claim_token"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	AdmittedScopeEpoch pgtype.Int8        `json:"admitted_scope_epoch"`
	ExecutionRunID     pgtype.UUID        `json:"execution_run_id"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceInvitation struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreateActionID  string             `json:"create_action_id"`
	CreatorRole     string             `json:"creator_role"`
	CodeHash        string             `json:"code_hash"`
	Role            string             `json:"role"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AcceptedBy      pgtype.UUID        `json:"accepted_by"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	AcceptedRunID   pgtype.UUID        `json:"accepted_run_id"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	RevokedBy       pgtype.UUID        `json:"revoked_by"`
	IssuedRunID     pgtype.UUID        `json:"issued_run_id"`
	IssuedAuthority []byte             `json:"issued_authority"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	PrincipalID pgtype.UUID `json:"principal_id"`
	Role        string      `json:"role"`
}
