// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Action struct {
	PrincipalID pgtype.UUID        `json:"principal_id"`
	ActionID    string             `json:"action_id"`
	RequestHash string             `json:"request_hash"`
	Receipt     []byte             `json:"receipt"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AgentExecutionPolicy struct {
	PrincipalID      pgtype.UUID `json:"principal_id"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ProactiveEnabled bool        `json:"proactive_enabled"`
	Version          int64       `json:"version"`
}

type Event struct {
	ID          int64              `json:"id"`
	RoomID      pgtype.UUID        `json:"room_id"`
	PrincipalID pgtype.UUID        `json:"principal_id"`
	ActionID    string             `json:"action_id"`
	Type        string             `json:"type"`
	Data        []byte             `json:"data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExecutionAction struct {
	RunID       pgtype.UUID        `json:"run_id"`
	ActionID    string             `json:"action_id"`
	RequestHash string             `json:"request_hash"`
	ActionType  string             `json:"action_type"`
	Payload     []byte             `json:"payload"`
	Receipt     []byte             `json:"receipt"`
	MessageID   pgtype.UUID        `json:"message_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExecutionEvent struct {
	RunID       pgtype.UUID        `json:"run_id"`
	EventID     string             `json:"event_id"`
	RequestHash string             `json:"request_hash"`
	Event       []byte             `json:"event"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExecutionRun struct {
	ID              pgtype.UUID        `json:"id"`
	ExecutorID      pgtype.UUID        `json:"executor_id"`
	PrincipalID     pgtype.UUID        `json:"principal_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ExecutorVersion int64              `json:"executor_version"`
	PolicyVersion   int64              `json:"policy_version"`
	ParentRunID     pgtype.UUID        `json:"parent_run_id"`
	Context         []byte             `json:"context"`
	Goal            string             `json:"goal"`
	Status          string             `json:"status"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Executor struct {
	ID              pgtype.UUID        `json:"id"`
	Issuer          string             `json:"issuer"`
	MachineSubject  string             `json:"machine_subject"`
	PrincipalID     pgtype.UUID        `json:"principal_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Enabled         bool               `json:"enabled"`
	Version         int64              `json:"version"`
	RuntimeVersion  string             `json:"runtime_version"`
	WorkflowVersion string             `json:"workflow_version"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ExternalIdentity struct {
	Issuer      string      `json:"issuer"`
	Subject     string      `json:"subject"`
	PrincipalID pgtype.UUID `json:"principal_id"`
}

type Message struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Content   string             `json:"content"`
	Seq       int64              `json:"seq"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Principal struct {
	ID          pgtype.UUID        `json:"id"`
	Kind        string             `json:"kind"`
	DisplayName string             `json:"display_name"`
	Disabled    bool               `json:"disabled"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Title        string             `json:"title"`
	Kind         string             `json:"kind"`
	Version      int64              `json:"version"`
	ScopeEpoch   int64              `json:"scope_epoch"`
	Stopped      bool               `json:"stopped"`
	RequireHuman bool               `json:"require_human"`
	Seq          int64              `json:"seq"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type RoomMember struct {
	RoomID      pgtype.UUID `json:"room_id"`
	PrincipalID pgtype.UUID `json:"principal_id"`
	Role        string      `json:"role"`
}

type TransportOutbox struct {
	ID                 int64              `json:"id"`
	EventID            int64              `json:"event_id"`
	Provider           string             `json:"provider"`
	Status             string             `json:"status"`
	Attempts           int32              `json:"attempts"`
	ProviderReceipt    []byte             `json:"provider_receipt"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ClaimToken         pgtype.UUID        `json:"claim_token"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	AdmittedScopeEpoch pgtype.Int8        `json:"admitted_scope_epoch"`
	ExecutionRunID     pgtype.UUID        `json:"execution_run_id"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	PrincipalID pgtype.UUID `json:"principal_id"`
	Role        string      `json:"role"`
}
