// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuthorizedRooms = `-- name: ListAuthorizedRooms :many
SELECT r.id::text AS id, r.workspace_id::text AS workspace_id, r.title, r.kind,
       r.version, r.scope_epoch, r.stopped
FROM rooms r
JOIN room_members m ON m.room_id=r.id
JOIN principals p ON p.id=m.principal_id
JOIN workspace_members wm ON wm.workspace_id=r.workspace_id AND wm.principal_id=m.principal_id
WHERE m.principal_id=$1::uuid AND NOT p.disabled AND r.id>$2::uuid
ORDER BY r.id LIMIT 101
`

type ListAuthorizedRoomsParams struct {
	PrincipalID pgtype.UUID `json:"principal_id"`
	AfterID     pgtype.UUID `json:"after_id"`
}

type ListAuthorizedRoomsRow struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Title       string `json:"title"`
	Kind        string `json:"kind"`
	Version     int64  `json:"version"`
	ScopeEpoch  int64  `json:"scope_epoch"`
	Stopped     bool   `json:"stopped"`
}

func (q *Queries) ListAuthorizedRooms(ctx context.Context, arg ListAuthorizedRoomsParams) ([]ListAuthorizedRoomsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizedRooms, arg.PrincipalID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorizedRoomsRow{}
	for rows.Next() {
		var i ListAuthorizedRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Kind,
			&i.Version,
			&i.ScopeEpoch,
			&i.Stopped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
