// Generated from the public reference recorded in assets/emoji/feishu-sources.json.
const officeClassicEmoji = <String, (String, String)>{
  "feishu:OK": ("OK", "assets/emoji/feishu/OK.png"),
  "feishu:THUMBSUP": ("点赞", "assets/emoji/feishu/THUMBSUP.png"),
  "feishu:THANKS": ("谢谢", "assets/emoji/feishu/THANKS.png"),
  "feishu:MUSCLE": ("加油", "assets/emoji/feishu/MUSCLE.png"),
  "feishu:FINGERHEART": ("比心", "assets/emoji/feishu/FINGERHEART.png"),
  "feishu:APPLAUSE": ("鼓掌", "assets/emoji/feishu/APPLAUSE.png"),
  "feishu:FISTBUMP": ("碰拳", "assets/emoji/feishu/FISTBUMP.png"),
  "feishu:JIAYI": ("加一", "assets/emoji/feishu/JIAYI.png"),
  "feishu:DONE": ("完成", "assets/emoji/feishu/DONE.png"),
  "feishu:SMILE": ("微笑", "assets/emoji/feishu/SMILE.png"),
  "feishu:BLUSH": ("愉快", "assets/emoji/feishu/BLUSH.png"),
  "feishu:LAUGH": ("大笑", "assets/emoji/feishu/LAUGH.png"),
  "feishu:SMIRK": ("偷笑", "assets/emoji/feishu/SMIRK.png"),
  "feishu:LOL": ("笑哭", "assets/emoji/feishu/LOL.png"),
  "feishu:FACEPALM": ("捂脸", "assets/emoji/feishu/FACEPALM.png"),
  "feishu:LOVE": ("爱你", "assets/emoji/feishu/LOVE.png"),
  "feishu:WINK": ("眨眼", "assets/emoji/feishu/WINK.png"),
  "feishu:PROUD": ("得意", "assets/emoji/feishu/PROUD.png"),
  "feishu:WITTY": ("机智", "assets/emoji/feishu/WITTY.png"),
  "feishu:SMART": ("聪明", "assets/emoji/feishu/SMART.png"),
  "feishu:SCOWL": ("皱眉", "assets/emoji/feishu/SCOWL.png"),
  "feishu:THINKING": ("思考", "assets/emoji/feishu/THINKING.png"),
  "feishu:SOB": ("流泪", "assets/emoji/feishu/SOB.png"),
  "feishu:CRY": ("哭泣", "assets/emoji/feishu/CRY.png"),
  "feishu:ERROR": ("尴尬", "assets/emoji/feishu/ERROR.png"),
  "feishu:NOSEPICK": ("抠鼻", "assets/emoji/feishu/NOSEPICK.png"),
  "feishu:HAUGHTY": ("傲慢", "assets/emoji/feishu/HAUGHTY.png"),
  "feishu:SLAP": ("打脸", "assets/emoji/feishu/SLAP.png"),
  "feishu:SPITBLOOD": ("吐血", "assets/emoji/feishu/SPITBLOOD.png"),
  "feishu:TOASTED": ("石化", "assets/emoji/feishu/TOASTED.png"),
  "feishu:GLANCE": ("看一眼", "assets/emoji/feishu/GLANCE.png"),
  "feishu:DULL": ("呆滞", "assets/emoji/feishu/DULL.png"),
  "feishu:INNOCENTSMILE": ("憨笑", "assets/emoji/feishu/INNOCENTSMILE.png"),
  "feishu:JOYFUL": ("开心", "assets/emoji/feishu/JOYFUL.png"),
  "feishu:WOW": ("哇", "assets/emoji/feishu/WOW.png"),
  "feishu:TRICK": ("坏笑", "assets/emoji/feishu/TRICK.png"),
  "feishu:YEAH": ("耶", "assets/emoji/feishu/YEAH.png"),
  "feishu:ENOUGH": ("够了", "assets/emoji/feishu/ENOUGH.png"),
  "feishu:TEARS": ("泪目", "assets/emoji/feishu/TEARS.png"),
  "feishu:EMBARRASSED": ("不好意思", "assets/emoji/feishu/EMBARRASSED.png"),
  "feishu:KISS": ("亲吻", "assets/emoji/feishu/KISS.png"),
  "feishu:SMOOCH": ("飞吻", "assets/emoji/feishu/SMOOCH.png"),
  "feishu:DROOL": ("流口水", "assets/emoji/feishu/DROOL.png"),
  "feishu:OBSESSED": ("色", "assets/emoji/feishu/OBSESSED.png"),
  "feishu:MONEY": ("发财", "assets/emoji/feishu/MONEY.png"),
  "feishu:TEASE": ("调皮", "assets/emoji/feishu/TEASE.png"),
  "feishu:SHOWOFF": ("嘚瑟", "assets/emoji/feishu/SHOWOFF.png"),
  "feishu:COMFORT": ("安慰", "assets/emoji/feishu/COMFORT.png"),
  "feishu:CLAP": ("拍手", "assets/emoji/feishu/CLAP.png"),
  "feishu:PRAISE": ("赞", "assets/emoji/feishu/PRAISE.png"),
  "feishu:STRIVE": ("奋斗", "assets/emoji/feishu/STRIVE.png"),
  "feishu:XBLUSH": ("脸红", "assets/emoji/feishu/XBLUSH.png"),
  "feishu:SILENT": ("闭嘴", "assets/emoji/feishu/SILENT.png"),
  "feishu:WAVE": ("挥手", "assets/emoji/feishu/WAVE.png"),
  "feishu:WHAT": ("疑问", "assets/emoji/feishu/WHAT.png"),
  "feishu:FROWN": ("委屈", "assets/emoji/feishu/FROWN.png"),
  "feishu:SHY": ("害羞", "assets/emoji/feishu/SHY.png"),
  "feishu:DIZZY": ("晕", "assets/emoji/feishu/DIZZY.png"),
  "feishu:LOOKDOWN": ("鄙视", "assets/emoji/feishu/LOOKDOWN.png"),
  "feishu:CHUCKLE": ("窃笑", "assets/emoji/feishu/CHUCKLE.png"),
  "feishu:WAIL": ("大哭", "assets/emoji/feishu/WAIL.png"),
  "feishu:CRAZY": ("抓狂", "assets/emoji/feishu/CRAZY.png"),
  "feishu:WHIMPER": ("抽泣", "assets/emoji/feishu/WHIMPER.png"),
  "feishu:HUG": ("抱抱", "assets/emoji/feishu/HUG.png"),
  "feishu:BLUBBER": ("嚎啕大哭", "assets/emoji/feishu/BLUBBER.png"),
  "feishu:WRONGED": ("可怜", "assets/emoji/feishu/WRONGED.png"),
  "feishu:HUSKY": ("二哈", "assets/emoji/feishu/HUSKY.png"),
  "feishu:SHHH": ("嘘", "assets/emoji/feishu/SHHH.png"),
  "feishu:SMUG": ("奸笑", "assets/emoji/feishu/SMUG.png"),
  "feishu:ANGRY": ("生气", "assets/emoji/feishu/ANGRY.png"),
  "feishu:HAMMER": ("敲打", "assets/emoji/feishu/HAMMER.png"),
  "feishu:SHOCKED": ("震惊", "assets/emoji/feishu/SHOCKED.png"),
  "feishu:TERROR": ("惊恐", "assets/emoji/feishu/TERROR.png"),
  "feishu:PETRIFIED": ("吓呆", "assets/emoji/feishu/PETRIFIED.png"),
  "feishu:SKULL": ("骷髅", "assets/emoji/feishu/SKULL.png"),
  "feishu:SWEAT": ("流汗", "assets/emoji/feishu/SWEAT.png"),
  "feishu:SPEECHLESS": ("无语", "assets/emoji/feishu/SPEECHLESS.png"),
  "feishu:SLEEP": ("睡觉", "assets/emoji/feishu/SLEEP.png"),
  "feishu:DROWSY": ("困", "assets/emoji/feishu/DROWSY.png"),
  "feishu:YAWN": ("哈欠", "assets/emoji/feishu/YAWN.png"),
  "feishu:SICK": ("生病", "assets/emoji/feishu/SICK.png"),
  "feishu:PUKE": ("呕吐", "assets/emoji/feishu/PUKE.png"),
  "feishu:BETRAYED": ("背叛", "assets/emoji/feishu/BETRAYED.png"),
  "feishu:HEADSET": ("耳机", "assets/emoji/feishu/HEADSET.png"),
  "feishu:EatingFood": ("吃饭", "assets/emoji/feishu/EatingFood.png"),
  "feishu:MeMeMe": ("我我我", "assets/emoji/feishu/MeMeMe.png"),
  "feishu:Sigh": ("叹气", "assets/emoji/feishu/Sigh.png"),
  "feishu:Typing": ("打字", "assets/emoji/feishu/Typing.png"),
  "feishu:Lemon": ("柠檬", "assets/emoji/feishu/Lemon.png"),
  "feishu:Get": ("收到", "assets/emoji/feishu/Get.png"),
  "feishu:LGTM": ("看起来不错", "assets/emoji/feishu/LGTM.png"),
  "feishu:OnIt": ("处理中", "assets/emoji/feishu/OnIt.png"),
  "feishu:OneSecond": ("稍等", "assets/emoji/feishu/OneSecond.png"),
  "feishu:VRHeadset": ("VR眼镜", "assets/emoji/feishu/VRHeadset.png"),
  "feishu:YouAreTheBest": ("你最棒", "assets/emoji/feishu/YouAreTheBest.png"),
  "feishu:SALUTE": ("敬礼", "assets/emoji/feishu/SALUTE.png"),
  "feishu:SHAKE": ("握手", "assets/emoji/feishu/SHAKE.png"),
  "feishu:HIGHFIVE": ("击掌", "assets/emoji/feishu/HIGHFIVE.png"),
  "feishu:UPPERLEFT": ("左上", "assets/emoji/feishu/UPPERLEFT.png"),
  "feishu:ThumbsDown": ("倒赞", "assets/emoji/feishu/ThumbsDown.png"),
  "feishu:SLIGHT": ("撇嘴", "assets/emoji/feishu/SLIGHT.png"),
  "feishu:TONGUE": ("吐舌", "assets/emoji/feishu/TONGUE.png"),
  "feishu:EYESCLOSED": ("闭眼", "assets/emoji/feishu/EYESCLOSED.png"),
  "feishu:RoarForYou": ("为你呐喊", "assets/emoji/feishu/RoarForYou.png"),
  "feishu:CALF": ("小牛", "assets/emoji/feishu/CALF.png"),
  "feishu:BEAR": ("熊", "assets/emoji/feishu/BEAR.png"),
  "feishu:BULL": ("牛", "assets/emoji/feishu/BULL.png"),
  "feishu:RAINBOWPUKE": ("彩虹", "assets/emoji/feishu/RAINBOWPUKE.png"),
  "feishu:ROSE": ("玫瑰", "assets/emoji/feishu/ROSE.png"),
  "feishu:HEART": ("爱心", "assets/emoji/feishu/HEART.png"),
  "feishu:PARTY": ("庆祝", "assets/emoji/feishu/PARTY.png"),
  "feishu:LIPS": ("嘴唇", "assets/emoji/feishu/LIPS.png"),
  "feishu:BEER": ("啤酒", "assets/emoji/feishu/BEER.png"),
  "feishu:CAKE": ("蛋糕", "assets/emoji/feishu/CAKE.png"),
  "feishu:GIFT": ("礼物", "assets/emoji/feishu/GIFT.png"),
  "feishu:CUCUMBER": ("黄瓜", "assets/emoji/feishu/CUCUMBER.png"),
  "feishu:Drumstick": ("鸡腿", "assets/emoji/feishu/Drumstick.png"),
  "feishu:Pepper": ("辣椒", "assets/emoji/feishu/Pepper.png"),
  "feishu:CANDIEDHAWS": ("糖葫芦", "assets/emoji/feishu/CANDIEDHAWS.png"),
  "feishu:BubbleTea": ("奶茶", "assets/emoji/feishu/BubbleTea.png"),
  "feishu:Coffee": ("咖啡", "assets/emoji/feishu/Coffee.png"),
  "feishu:Yes": ("是", "assets/emoji/feishu/Yes.png"),
  "feishu:No": ("否", "assets/emoji/feishu/No.png"),
  "feishu:OKR": ("OKR", "assets/emoji/feishu/OKR.png"),
  "feishu:CheckMark": ("对勾", "assets/emoji/feishu/CheckMark.png"),
  "feishu:CrossMark": ("叉号", "assets/emoji/feishu/CrossMark.png"),
  "feishu:MinusOne": ("减一", "assets/emoji/feishu/MinusOne.png"),
  "feishu:Hundred": ("一百分", "assets/emoji/feishu/Hundred.png"),
  "feishu:AWESOMEN": ("酷", "assets/emoji/feishu/AWESOMEN.png"),
  "feishu:Pin": ("图钉", "assets/emoji/feishu/Pin.png"),
  "feishu:Alarm": ("闹钟", "assets/emoji/feishu/Alarm.png"),
  "feishu:Loudspeaker": ("喇叭", "assets/emoji/feishu/Loudspeaker.png"),
  "feishu:Trophy": ("奖杯", "assets/emoji/feishu/Trophy.png"),
  "feishu:Fire": ("火", "assets/emoji/feishu/Fire.png"),
  "feishu:BOMB": ("炸弹", "assets/emoji/feishu/BOMB.png"),
  "feishu:Music": ("音乐", "assets/emoji/feishu/Music.png"),
  "feishu:XmasTree": ("圣诞树", "assets/emoji/feishu/XmasTree.png"),
  "feishu:Snowman": ("雪人", "assets/emoji/feishu/Snowman.png"),
  "feishu:XmasHat": ("圣诞帽", "assets/emoji/feishu/XmasHat.png"),
  "feishu:FIREWORKS": ("烟花", "assets/emoji/feishu/FIREWORKS.png"),
  "feishu:2022": ("2022", "assets/emoji/feishu/2022.png"),
  "feishu:REDPACKET": ("红包", "assets/emoji/feishu/REDPACKET.png"),
  "feishu:FORTUNE": ("福", "assets/emoji/feishu/FORTUNE.png"),
  "feishu:LUCK": ("好运", "assets/emoji/feishu/LUCK.png"),
  "feishu:FIRECRACKER": ("鞭炮", "assets/emoji/feishu/FIRECRACKER.png"),
  "feishu:StickyRiceBalls": ("汤圆", "assets/emoji/feishu/StickyRiceBalls.png"),
  "feishu:HEARTBROKEN": ("心碎", "assets/emoji/feishu/HEARTBROKEN.png"),
  "feishu:POOP": ("便便", "assets/emoji/feishu/POOP.png"),
  "feishu:StatusFlashOfInspiration": (
    "灵感",
    "assets/emoji/feishu/StatusFlashOfInspiration.png",
  ),
  "feishu:18X": ("十八禁", "assets/emoji/feishu/18X.png"),
  "feishu:CLEAVER": ("菜刀", "assets/emoji/feishu/CLEAVER.png"),
  "feishu:Soccer": ("足球", "assets/emoji/feishu/Soccer.png"),
  "feishu:Basketball": ("篮球", "assets/emoji/feishu/Basketball.png"),
  "feishu:GeneralDoNotDisturb": (
    "免打扰",
    "assets/emoji/feishu/GeneralDoNotDisturb.png",
  ),
  "feishu:Status_PrivateMessage": (
    "私信",
    "assets/emoji/feishu/Status_PrivateMessage.png",
  ),
  "feishu:GeneralInMeetingBusy": (
    "会议中",
    "assets/emoji/feishu/GeneralInMeetingBusy.png",
  ),
  "feishu:StatusReading": ("阅读中", "assets/emoji/feishu/StatusReading.png"),
  "feishu:StatusInFlight": ("飞行中", "assets/emoji/feishu/StatusInFlight.png"),
  "feishu:GeneralBusinessTrip": (
    "出差",
    "assets/emoji/feishu/GeneralBusinessTrip.png",
  ),
  "feishu:GeneralWorkFromHome": (
    "居家办公",
    "assets/emoji/feishu/GeneralWorkFromHome.png",
  ),
  "feishu:StatusEnjoyLife": ("享受生活", "assets/emoji/feishu/StatusEnjoyLife.png"),
  "feishu:GeneralTravellingCar": (
    "驾车",
    "assets/emoji/feishu/GeneralTravellingCar.png",
  ),
  "feishu:StatusBus": ("公交", "assets/emoji/feishu/StatusBus.png"),
  "feishu:GeneralSun": ("太阳", "assets/emoji/feishu/GeneralSun.png"),
  "feishu:GeneralMoonRest": ("休息", "assets/emoji/feishu/GeneralMoonRest.png"),
  "feishu:MoonRabbit": ("玉兔", "assets/emoji/feishu/MoonRabbit.png"),
  "feishu:Mooncake": ("月饼", "assets/emoji/feishu/Mooncake.png"),
  "feishu:JubilantRabbit": ("欢乐兔", "assets/emoji/feishu/JubilantRabbit.png"),
  "feishu:TV": ("电视", "assets/emoji/feishu/TV.png"),
  "feishu:Movie": ("电影", "assets/emoji/feishu/Movie.png"),
  "feishu:Pumpkin": ("南瓜", "assets/emoji/feishu/Pumpkin.png"),
  "feishu:BeamingFace": ("笑逐颜开", "assets/emoji/feishu/BeamingFace.png"),
  "feishu:Delighted": ("喜悦", "assets/emoji/feishu/Delighted.png"),
  "feishu:ColdSweat": ("冷汗", "assets/emoji/feishu/ColdSweat.png"),
  "feishu:FullMoonFace": ("满月脸", "assets/emoji/feishu/FullMoonFace.png"),
  "feishu:Partying": ("派对", "assets/emoji/feishu/Partying.png"),
  "feishu:GoGoGo": ("冲冲冲", "assets/emoji/feishu/GoGoGo.png"),
  "feishu:ThanksFace": ("感谢", "assets/emoji/feishu/ThanksFace.png"),
  "feishu:SaluteFace": ("敬礼脸", "assets/emoji/feishu/SaluteFace.png"),
  "feishu:Shrug": ("耸肩", "assets/emoji/feishu/Shrug.png"),
  "feishu:ClownFace": ("小丑", "assets/emoji/feishu/ClownFace.png"),
  "feishu:HappyDragon": ("欢乐龙", "assets/emoji/feishu/HappyDragon.png"),
};
